// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace JsonFormatter
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidJsonFormatterPackageString = "6910058c-448f-4103-9423-50276145f338";
        public static Guid guidJsonFormatterPackage = new Guid(guidJsonFormatterPackageString);

        public const string guidJsonFormatterPackageCmdSetString = "25e9462e-b849-4317-bcfd-8cdea538f8b3";
        public static Guid guidJsonFormatterPackageCmdSet = new Guid(guidJsonFormatterPackageCmdSetString);

        public const string guidMinifyString = "399a2d9d-b0e5-4737-b441-a80be8acb1e3";
        public static Guid guidMinify = new Guid(guidMinifyString);

        public const string guidPrettyString = "3b6d80d0-9493-4ff6-a7ec-c7c1150f2b9e";
        public static Guid guidPretty = new Guid(guidPrettyString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MinifyJsonCommand = 0x0100;
        public const int PrettyJsonCommand = 0x0200;
        public const int Toolbar = 0x1000;
        public const int ToolbarGroup = 0x1050;
        public const int bmpMinify = 0x0001;
        public const int bmpPretty = 0x0001;
    }
}