// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace JsonFormatter
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidJsonFormatterPackageString = "6910058c-448f-4103-9423-50276145f338";
        public static Guid guidJsonFormatterPackage = new Guid(guidJsonFormatterPackageString);

        public const string guidJsonFormatterPackageCmdSetString = "25e9462e-b849-4317-bcfd-8cdea538f8b3";
        public static Guid guidJsonFormatterPackageCmdSet = new Guid(guidJsonFormatterPackageCmdSetString);

        public const string guidImagesString = "376e1888-36e4-4298-82ca-c9ee0015e00b";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int MinifyJsonCommand = 0x0100;
        public const int PrettyJsonCommand = 0x0200;
        public const int Toolbar = 0x1000;
        public const int ToolbarGroup = 0x1050;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}